---
channel: stable
addons:
  paperless-ngx:
    repository: BenoitAnastay/paperless-home-assistant-addon
    target: paperless-ngx
    image: ghcr.io/benoitanastay/paperless-ngx/{arch}
  dashy:
    repository: BenoitAnastay/dashy-home-assistant-addon
    target: dashy
    image: ghcr.io/benoitanastay/dashy/{arch}
  heimdall:
    repository: BenoitAnastay/heimdall-home-assistant-addon
    target: heimdall
    image: ghcr.io/benoitanastay/heimdall/{arch}
