name: Dashy
version: 0.1.2
slug: dashy
url: https://dashy.to/
init: false
description: Dashy is an open source, highly customizable, easy to use, privacy-respecting
  dashboard app
webui: http://[HOST]:[PORT:8080]
stage: experimental
arch:
- aarch64
- amd64
ports:
  8080/tcp: 8080
ports_description:
  8080/tcp: Web interface
map:
- addon_config:rw
image: ghcr.io/benoitanastay/dashy/{arch}
